#!/usr/bin/env python3
"""PlatformIO 预编译脚本：把 config/default_motion.json 生成 C++ 默认值。

生成 lib/motion_control/defaults_generated.h，其中 apply_generated_defaults()
用各 public setter 写入默认值。NVS 有保存值时会在 _load_* 阶段覆盖它们，
没有保存时即使用这里的默认。

由 platformio.ini 的 extra_scripts = pre:scripts/gen_defaults.py 触发。
"""
Import("env")  # noqa: F821  (SCons 提供)

import json
import os

PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821
JSON_PATH = os.path.join(PROJECT_DIR, "config", "default_motion.json")
OUT_PATH = os.path.join(PROJECT_DIR, "lib", "motion_control", "defaults_generated.h")
MODE_OUT_PATH = os.path.join(PROJECT_DIR, "lib", "system", "default_mode_generated.h")

MOTORS = ("left_front", "left_back", "right_front", "right_back")
LOOPS = ("position", "line_speed", "angle_speed")
COMTYPE_MAP = {"wifi": 0, "bluetooth": 1, "ps3": 2}


def fnum(value):
    text = f"{float(value):.6g}"
    if "." not in text and "e" not in text and "E" not in text:
        text += ".0"
    return text + "f"


def inum(value):
    return str(int(value))


def bnum(value):
    return "true" if value else "false"


def motor_lines(motor, data):
    return [
        "    mc.set_{m}_motor_config_params({a}, {b}, {ea}, {eb}, {pwm}, {dia}, {ppr}, {rpm});".format(
            m=motor,
            a=inum(data["motor_pina"]),
            b=inum(data["motor_pinb"]),
            ea=inum(data["encoder_pina"]),
            eb=inum(data["encoder_pinb"]),
            pwm=inum(data["motor_pinpwm"]),
            dia=fnum(data["wheel_diameter"]),
            ppr=inum(data["pluses_per_revolution"]),
            rpm=inum(data["revolutions_per_minute"]),
        ),
        "    mc.set_{m}_motor_pid_params({p}, {i}, {d}, {mi});".format(
            m=motor,
            p=fnum(data["pid"]["p"]),
            i=fnum(data["pid"]["i"]),
            d=fnum(data["pid"]["d"]),
            mi=fnum(data["pid"]["max_total_integral"]),
        ),
    ]


def build_body():
    if not os.path.isfile(JSON_PATH):
        return "    // 未找到 config/default_motion.json，使用代码内置默认值"

    with open(JSON_PATH, "r", encoding="utf-8") as f:
        doc = json.load(f)

    try:
        motion = doc["motion"]
        lines = [
            f'    mc.set_wheel_type({bnum(motion["is_mecanum_wheel"])});',
            "    mc.set_model_params({}, {});".format(
                fnum(motion["track_width"]), fnum(motion["wheel_width"])),
            f'    mc.set_milliseconds({inum(motion["milliseconds"])});',
            "    mc.set_loop_period_cnt({}, {});".format(
                inum(motion["position_loop_milliseconds_cnt"]),
                inum(motion["speed_loop_milliseconds_cnt"])),
            f'    mc.set_speed_plan_state({bnum(motion["enable_speed_plan"])});',
            f'    mc.set_motor_enable_flags({inum(motion["motor_enable_flags"])});',
            "    mc.set_speed_plan_parms({}, {}, {});".format(
                fnum(motion["max_v"]), fnum(motion["max_acc"]), fnum(motion["jerk"])),
        ]

        for loop in LOOPS:
            pid = doc["pid_loops"][loop]
            lines.append("    mc.set_{}_pid_params({}, {}, {}, {});".format(
                loop, fnum(pid["p"]), fnum(pid["i"]), fnum(pid["d"]),
                fnum(pid["max_total_integral"])))

        for motor in MOTORS:
            lines.extend(motor_lines(motor, doc["motors"][motor]))

        return "\n".join(lines)
    except (KeyError, TypeError) as exc:
        return f"    // 默认配置解析失败，忽略: {exc}"


CONTENT = """// AUTO-GENERATED by scripts/gen_defaults.py from config/default_motion.json
// 请勿手改；修改 JSON 后重新编译即可。
#pragma once

#include "motionControl.h"

inline void apply_generated_defaults(MotionControl &mc) {{
{body}
}}
""".format(body=build_body())

os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
with open(OUT_PATH, "w", encoding="utf-8") as f:
    f.write(CONTENT)

print(f"[gen_defaults] wrote {OUT_PATH}")


def build_default_comtype():
    if not os.path.isfile(JSON_PATH):
        return 0
    with open(JSON_PATH, "r", encoding="utf-8") as f:
        doc = json.load(f)
    name = str(doc.get("comtype", "wifi")).lower()
    if name not in COMTYPE_MAP:
        print(f"[gen_defaults] 未知 comtype '{name}'，回退为 wifi")
    return COMTYPE_MAP.get(name, 0)


MODE_CONTENT = """// AUTO-GENERATED by scripts/gen_defaults.py from config/default_motion.json
// 请勿手改；修改 JSON 后重新编译即可。
#pragma once

static constexpr int DEFAULT_COMMUNICATION_TYPE = {value}; // 0=wifi 1=bluetooth 2=ps3
""".format(value=build_default_comtype())

os.makedirs(os.path.dirname(MODE_OUT_PATH), exist_ok=True)
with open(MODE_OUT_PATH, "w", encoding="utf-8") as f:
    f.write(MODE_CONTENT)

print(f"[gen_defaults] wrote {MODE_OUT_PATH}")
